name: 'Build and Publish GitBook'
description: 'Build GitBook static site files and deploy to GitHub Pages.'
author: 'a920604a (yuan)'
branding:
  icon: 'book'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'